blank_issues_enabled: false
contact_links:
    - name: 💻 Facebook Community
      url: https://www.facebook.com/compourri
      about: Join our Facebook Community to chat with other users in the Software Essentials community.
